### ISSUE TITLE
image fails when FLIGHTAWARE_GPS_HOST is not specified

### ISSUE THREAD

**Issue by hakan42** [ShoGinn/flightaware#1]
Currently, I have to specify FLIGHTAWARE_GPS_HOST , else the image fails in line 15

**Comment by ShoGinn** [comment]
should be fixed with https://github.com/ShoGinn/flightaware/commit/fb00e656310996836733efac42dcbddb0033f87f

**Comment by ShoGinn** [comment]
closing since nothing heard.
