### ISSUE TITLE
very high load if FLIGHTAWARE_GPS_HOST is set to 127.0.0.1

### ISSUE THREAD

**Issue by hakan42** [ShoGinn/flightaware#2]
To get around issue #1 , I had set the FLIGHTAWARE_GPS_HOST to localhost. Which in turn caused the docker image to consume all available CPU (understantably, as it was socat'ing from itself to itself in an endless loop). I had to do a hard reset as I couldn't even use my shells.

if the variable is set to such a dangerous value, it should stop so the error cause is immediately visible.

**Comment by ShoGinn** [comment]
I don't plan on changing it to check for any IP... but I did fix the issue #1 with https://github.com/ShoGinn/flightaware/commit/fb00e656310996836733efac42dcbddb0033f87f

**Comment by hakan42** [comment]
o.k.
